### ISSUE TITLE
Theme review

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/lawyeriax-lite#47]
- Validate and/or sanitize untrusted data before entering into the database. All untrusted data should be escaped before output. Some data needs to be escaped, such as `$icon->icon_value` in header.php file.

- Don't prefix libraries of script/styles/fonts. Libraries can be used by plugins as well so they don't need to be prefixed.

- Slider control isn't allowed. If it adds only image, it will be allowed. But because it's repeatable + it adds text and button, it won't be.

- There's a fist-page.php for no reason?

- Apart form that, theme should use the new tags for style.css file.

That's all.

**Comment by rodica-andronache** [comment]
@Hardeep thanks for the review :) you already had an issue assigned for this https://github.com/Codeinwp/lawyeriax-lite/issues/45. No need to create another one
