### ISSUE TITLE
LawyeriaX page on themeisle

### ISSUE THREAD

**Issue by cristian-ungureanu** [Codeinwp/lawyeriax-lite#57]
@rodica-andronache, @abaicus Theme URI in style.css is 404 refer.

**Comment by abaicus** [comment]
@rodica-andronache Te rog cand poti sa arunci un ochi peste ce am facut. Am pus tot ce trebuie. Cred ca e si sincronizat cu git. Ar trebui totusi adaugat demo-ul in demo bar si nu am aces in adminer.
