### ISSUE TITLE
[wporg review] Escaping

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/lawyeriax-lite#70]
Do not use esc_html() or esc_html_e() to escape an attribute. Use esc_attr(), esc_attr(), esc_attr_e() or esc_attr_x() , file: lawyeriax-lite\inc\class\repeater-general-control.php, line: 70
Do not use esc_html() or esc_html_e() to escape an attribute. Use esc_attr(), esc_attr(), esc_attr_e() or esc_attr_x() , file: lawyeriax-lite\inc\class\repeater-general-control.php, line: 91
Do not use esc_html() or esc_html_e() to escape an attribute. Use esc_attr(), esc_attr(), esc_attr_e() or esc_attr_x() , file: lawyeriax-lite\inc\class\repeater-general-control.php, line: 112
Do not use esc_html() or esc_html_e() to escape an attribute. Use esc_attr(), esc_attr(), esc_attr_e() or esc_attr_x() , file: lawyeriax-lite\inc\class\repeater-general-control.php, line: 118
Do not use esc_html() or esc_html_e() to escape an attribute. Use esc_attr(), esc_attr(), esc_attr_e() or esc_attr_x() , file: lawyeriax-lite\inc\class\repeater-general-control.php, line: 123
Do not use esc_html() or esc_html_e() to escape an attribute. Use esc_attr(), esc_attr(), esc_attr_e() or esc_attr_x() , file: lawyeriax-lite\inc\class\repeater-general-control.php, line: 127
Do not use esc_html() or esc_html_e() to escape an attribute. Use esc_attr(), esc_attr(), esc_attr_e() or esc_attr_x() , file: lawyeriax-lite\inc\class\repeater-general-control.php, line: 153
Do not use esc_html() or esc_html_e() to escape an attribute. Use esc_attr(), esc_attr(), esc_attr_e() or esc_attr_x() , file: lawyeriax-lite\inc\class\repeater-general-control.php, line: 176
Do not use esc_html() or esc_html_e() to escape an attribute. Use esc_attr(), esc_attr(), esc_attr_e() or esc_attr_x() , file: lawyeriax-lite\inc\class\repeater-general-control.php, line: 196
Do not use esc_html() or esc_html_e() to escape an attribute. Use esc_attr(), esc_attr(), esc_attr_e() or esc_attr_x() , file: lawyeriax-lite\inc\class\repeater-general-control.php, line: 202
Do not use esc_html() or esc_html_e() to escape an attribute. Use esc_attr(), esc_attr(), esc_attr_e() or esc_attr_x() , file: lawyeriax-lite\inc\class\repeater-general-control.php, line: 207
Do not use esc_html() or esc_html_e() to escape an attribute. Use esc_attr(), esc_attr(), esc_attr_e() or esc_attr_x() , file: lawyeriax-lite\inc\class\repeater-general-control.php, line: 211
Do not use esc_html() or esc_html_e() to escape an attribute. Use esc_attr(), esc_attr(), esc_attr_e() or esc_attr_x() , file: lawyeriax-lite\inc\class\repeater-general-control.php, line: 241
Do not use esc_html() or esc_html_e() to escape an attribute. Use esc_attr(), esc_attr(), esc_attr_e() or esc_attr_x() , file: lawyeriax-lite\inc\class\repeater-general-control.php, line: 264
Do not use esc_html() or esc_html_e() to escape an attribute. Use esc_attr(), esc_attr(), esc_attr_e() or esc_attr_x() , file: lawyeriax-lite\inc\class\repeater-general-control.php, line: 284
Do not use esc_html() or esc_html_e() to escape an attribute. Use esc_attr(), esc_attr(), esc_attr_e() or esc_attr_x() , file: lawyeriax-lite\inc\class\repeater-general-control.php, line: 290
Do not use esc_html() or esc_html_e() to escape an attribute. Use esc_attr(), esc_attr(), esc_attr_e() or esc_attr_x() , file: lawyeriax-lite\inc\class\repeater-general-control.php, line: 295
Do not use esc_html() or esc_html_e() to escape an attribute. Use esc_attr(), esc_attr(), esc_attr_e() or esc_attr_x() , file: lawyeriax-lite\inc\class\repeater-general-control.php, line: 299

**Comment by rodica-andronache** [comment]
I don't understand what you did here :) You replaced the repeater control, but didn't fix the exact issues mentioned by the reviewer

**Comment by cristian-ungureanu** [comment]
Yes I did ... esc_attr is used when you echo a variable in  html atribute, something like
 `<div class="<?php echo esc_attr($some_class_name); ?>" >` . 
We can use esc_html in this situation:
`<div> <?php echo esc_html($some_variable); ?> </div>`

**Comment by rodica-andronache** [comment]
there were still some issues, causing theme check errors
