### ISSUE TITLE
[wporg review]  translatable strings

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/lawyeriax-lite#73]
All theme text strings are to be translatable.

Strings should have translatable content , file: lawyeriax-lite\inc\template-tags.php, line: 54
Strings should have translatable content , file: lawyeriax-lite\inc\template-tags.php, line: 60

@cristian-ungureanu i didn't see the strings he's mentioning, but I thought that maybe you can also have a look

**Comment by cristian-ungureanu** [comment]
there were variable content in __ function ... took it form twenty fifteen now
