### ISSUE TITLE
[wporg review] Remove the top bar by default

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/lawyeriax-lite#75]
Use sane defaults and don’t write default setting values to the database.

Do not display the top bar by default. What if users do not want this feature?.
ref: https://make.wordpress.org/themes/2016/03/31/what-is-demo-content/

**Comment by cristian-ungureanu** [comment]
@rodica-andronache , I added this but what about the users that already have the theme?

**Comment by rodica-andronache** [comment]
I don't know other solution here, and i'm not sure if it's worth to spend more time, as we only have like 1000 users
