### ISSUE TITLE
Better integrate with Nivo Slider Lite

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/lawyeriax-lite#83]
https://wordpress.org/plugins/nivo-slider-lite/

Right now the captions look like this http://prntscr.com/d7iy8y

**Comment by claudiuvertistudio** [comment]
@rodica-andronache on frontpage doesn't load css file of the Nivo slider plugin. Seems to be a problem from the plugin

we can put the css file of the plugin in the theme. I don't know if this is the best solution

**Comment by rodica-andronache** [comment]
@claudiuvertistudio we have the slider now https://github.com/Codeinwp/nivo-slider-lite . you can check out if the problem is with the plugin or with the theme

**Comment by claudiuvertistudio** [comment]
@rodica-andronache I know and I have tested and it doesn't work.

**Comment by rodica-andronache** [comment]
and we can't do anything? in the theme or plugin?

**Comment by claudiuvertistudio** [comment]
yes, we can copy css from the plugin into our theme. @rodica-andronache
